import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import "./Generate.css";

const API_BASE = "http://localhost:5000";

const getAuthToken = () => localStorage.getItem("authToken");

const getAuthHeaders = (extra = {}) => ({
  ...extra,
  Authorization: `Bearer ${getAuthToken()}`,
});

const colorSchemes = [
  {
    id: "vibrant",
    name: "Vibrant",
    swatch: "linear-gradient(90deg,#22d3ee,#f43f5e,#f97316)",
  },
  {
    id: "ocean",
    name: "Ocean",
    swatch: "linear-gradient(90deg,#0ea5e9,#22d3ee,#0f766e)",
  },
  {
    id: "mint",
    name: "Mint",
    swatch: "linear-gradient(90deg,#10b981,#6ee7b7,#22c55e)",
  },
  {
    id: "orchid",
    name: "Orchid",
    swatch: "linear-gradient(90deg,#8b5cf6,#a855f7,#c084fc)",
  },
  {
    id: "mono",
    name: "Mono",
    swatch: "linear-gradient(90deg,#6b7280,#9ca3af,#d1d5db)",
  },
  {
    id: "neon",
    name: "Neon",
    swatch: "linear-gradient(90deg,#06b6d4,#e879f9,#fde047)",
  },
  {
    id: "blush",
    name: "Blush",
    swatch: "linear-gradient(90deg,#fca5a5,#fbcfe8,#fecdd3)",
  },
];

const styles = ["Bold & Graphic", "Minimal & Clean", "Cinematic", "Retro Wave"];
const ratios = ["16:9", "1:1", "9:16"];
const outputTypes = [
  "Product Marketing Mockup",
  "Lifestyle Scene",
  "Studio Ad",
  "Landing Page Hero",
  "Social Media Creative",
];
const loadingMessages = [
  "Analyzing product contours and edges...",
  "Building scene composition and depth...",
  "Applying style, lighting, and brand color mood...",
  "Finalizing export-ready creative...",
];

const getAspectDimensions = (ratio) => {
  if (ratio === "1:1") return { width: 1080, height: 1080 };
  if (ratio === "9:16") return { width: 1080, height: 1920 };
  return { width: 1600, height: 900 };
};

const createMockCreativeDataUrl = ({
  title,
  outputType,
  aspectRatio,
  thumbnailStyle,
  colorScheme,
  additionalPrompts,
}) => {
  const { width, height } = getAspectDimensions(aspectRatio);
  const safeTitle = title || "Campaign Creative";
  const safePrompt =
    additionalPrompts || "Balanced lighting with premium product focus";
  const svg = `
  <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#03141a"/>
        <stop offset="100%" stop-color="#0a2630"/>
      </linearGradient>
      <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stop-color="#00C9FF"/>
        <stop offset="50%" stop-color="#92FE9D"/>
        <stop offset="100%" stop-color="#00C9FF"/>
      </linearGradient>
      <filter id="blur"><feGaussianBlur stdDeviation="45"/></filter>
    </defs>
    <rect width="100%" height="100%" fill="url(#bg)"/>
    <circle cx="${Math.round(width * 0.2)}" cy="${Math.round(height * 0.15)}" r="${Math.round(width * 0.15)}" fill="#00C9FF" opacity="0.3" filter="url(#blur)"/>
    <circle cx="${Math.round(width * 0.8)}" cy="${Math.round(height * 0.75)}" r="${Math.round(width * 0.22)}" fill="#92FE9D" opacity="0.22" filter="url(#blur)"/>
    <rect x="${Math.round(width * 0.08)}" y="${Math.round(height * 0.1)}" width="${Math.round(width * 0.84)}" height="${Math.round(height * 0.8)}" rx="26" fill="rgba(255,255,255,0.04)" stroke="rgba(255,255,255,0.2)"/>
    <text x="${Math.round(width * 0.12)}" y="${Math.round(height * 0.24)}" fill="#EAFBFF" font-size="${Math.round(width * 0.042)}" font-family="Arial, sans-serif" font-weight="700">${safeTitle}</text>
    <text x="${Math.round(width * 0.12)}" y="${Math.round(height * 0.33)}" fill="#BFE4EC" font-size="${Math.round(width * 0.022)}" font-family="Arial, sans-serif">${outputType} • ${aspectRatio} • ${thumbnailStyle}</text>
    <text x="${Math.round(width * 0.12)}" y="${Math.round(height * 0.39)}" fill="#BFE4EC" font-size="${Math.round(width * 0.018)}" font-family="Arial, sans-serif">${safePrompt.slice(0, 85)}</text>
    <rect x="${Math.round(width * 0.12)}" y="${Math.round(height * 0.47)}" width="${Math.round(width * 0.26)}" height="${Math.round(height * 0.36)}" rx="18" fill="url(#accent)" opacity="0.88"/>
    <text x="${Math.round(width * 0.135)}" y="${Math.round(height * 0.8)}" fill="#03141a" font-size="${Math.round(width * 0.02)}" font-family="Arial, sans-serif" font-weight="700">${colorScheme.name} Mood</text>
    <text x="${Math.round(width * 0.12)}" y="${Math.round(height * 0.91)}" fill="#8FB8C2" font-size="${Math.round(width * 0.016)}" font-family="Arial, sans-serif">Generated by BrandForge AI</text>
  </svg>`;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
};

const Generate = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [title, setTitle] = useState("");
  const [aspectRatio, setAspectRatio] = useState("16:9");
  const [thumbnailStyle, setThumbnailStyle] = useState(styles[0]);
  const [colorScheme, setColorScheme] = useState(colorSchemes[0]);
  const [model, setModel] = useState("premium");
  const [outputType, setOutputType] = useState(outputTypes[0]);
  const [additionalPrompts, setAdditionalPrompts] = useState("");
  const [productImageFile, setProductImageFile] = useState(null);
  const [productImageName, setProductImageName] = useState("");
  const [sourcePreviewUrl, setSourcePreviewUrl] = useState("");
  const [generatedCreative, setGeneratedCreative] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [loadingIndex, setLoadingIndex] = useState(0);
  const [feedback, setFeedback] = useState({ tone: "info", text: "" });
  const loadingIntervalRef = useRef(null);

  const titleCount = useMemo(() => title.length, [title]);
  const storageKey = useMemo(
    () => (id ? `brandforge_creative_${id}` : ""),
    [id],
  );

  useEffect(() => {
    return () => {
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
      }
      if (sourcePreviewUrl) {
        URL.revokeObjectURL(sourcePreviewUrl);
      }
    };
  }, [sourcePreviewUrl]);

  useEffect(() => {
    if (!id) return;

    const token = getAuthToken();
    if (!token) {
      setFeedback({
        tone: "error",
        text: "Please login to access this creative.",
      });
      navigate("/login");
      return;
    }

    const loadCreative = async () => {
      try {
        const response = await fetch(`${API_BASE}/api/creatives/${id}`, {
          headers: getAuthHeaders(),
        });
        const data = await response.json();

        if (!response.ok || !data.success) {
          throw new Error(data.message || "Creative not found");
        }

        const parsed = data.creative;
        setTitle(parsed.title || "");
        setAspectRatio(parsed.aspectRatio || "16:9");
        setThumbnailStyle(parsed.thumbnailStyle || styles[0]);
        setModel(parsed.model || "premium");
        setOutputType(parsed.outputType || outputTypes[0]);
        setAdditionalPrompts(parsed.additionalPrompts || "");
        setProductImageName(parsed.productImageName || "");
        const selectedScheme = colorSchemes.find(
          (scheme) => scheme.id === parsed.colorSchemeId,
        );
        setColorScheme(selectedScheme || colorSchemes[0]);
        setGeneratedCreative(parsed);
        setFeedback({
          tone: "info",
          text: "Loaded creative from your account.",
        });
      } catch {
        // Optional fallback for old local-only items
        if (storageKey) {
          const raw = sessionStorage.getItem(storageKey);
          if (raw) {
            try {
              const parsed = JSON.parse(raw);
              setGeneratedCreative(parsed);
              return;
            } catch {}
          }
        }
        setFeedback({
          tone: "error",
          text: "Unable to load this creative.",
        });
      }
    };

    loadCreative();
  }, [id, storageKey, navigate]);

  const handlePhotoChange = (event) => {
    const file = event.target.files?.[0];
    if (!file) {
      setProductImageFile(null);
      setProductImageName("");
      if (sourcePreviewUrl) {
        URL.revokeObjectURL(sourcePreviewUrl);
        setSourcePreviewUrl("");
      }
      return;
    }

    if (sourcePreviewUrl) {
      URL.revokeObjectURL(sourcePreviewUrl);
    }

    const objectUrl = URL.createObjectURL(file);
    setProductImageFile(file);
    setSourcePreviewUrl(objectUrl);
    setProductImageName(file.name);
    setFeedback({
      tone: "info",
      text: "Product image attached. Ready to generate.",
    });
  };

  const handleGenerate = async () => {
    if (!title.trim()) {
      setFeedback({
        tone: "error",
        text: "Add a product or campaign title before generating.",
      });
      return;
    }

    if (!productImageFile) {
      setFeedback({
        tone: "error",
        text: "Upload a product image to generate creative output.",
      });
      return;
    }

    const token = getAuthToken();
    if (!token) {
      setFeedback({
        tone: "error",
        text: "Please login to generate creatives.",
      });
      navigate("/login");
      return;
    }

    setIsLoading(true);
    setLoadingIndex(0);
    setFeedback({
      tone: "info",
      text: "Generation started. This usually takes a few seconds.",
    });

    loadingIntervalRef.current = setInterval(() => {
      setLoadingIndex((prev) => (prev + 1) % loadingMessages.length);
    }, 850);

    try {
      // 1) Upload source image
      const formData = new FormData();
      formData.append("image", productImageFile);

      const uploadRes = await fetch(`${API_BASE}/api/media/upload-source`, {
        method: "POST",
        headers: getAuthHeaders(),
        body: formData,
      });
      const uploadData = await uploadRes.json();
      if (!uploadRes.ok || !uploadData.success) {
        throw new Error(uploadData.message || "Source image upload failed");
      }

      // 2) Generate image via backend
      const genPayload = {
        sourceImageUrl: uploadData.sourceImageUrl,
        title,
        outputType,
        aspectRatio,
        thumbnailStyle,
        colorSchemeId: colorScheme.id,
        model,
        additionalPrompts,
        productImageName,
      };

      const genRes = await fetch(`${API_BASE}/api/generations/generate`, {
        method: "POST",
        headers: getAuthHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify(genPayload),
      });
      const genData = await genRes.json();
      if (!genRes.ok || !genData.success) {
        throw new Error(genData.message || "Generation failed");
      }

      // 3) Save metadata in MongoDB
      const savePayload = {
        ...genPayload,
        imageUrl: genData.generatedImageUrl,
        prompt: genData.prompt || "",
        sourceImageUrl: uploadData.sourceImageUrl,
        generatedPublicId: genData.generatedPublicId || "",
      };

      const saveRes = await fetch(`${API_BASE}/api/creatives`, {
        method: "POST",
        headers: getAuthHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify(savePayload),
      });
      const saveData = await saveRes.json();
      if (!saveRes.ok || !saveData.success) {
        throw new Error(saveData.message || "Saving creative failed");
      }

      const created = saveData.creative;
      setGeneratedCreative(created);
      setFeedback({
        tone: "success",
        text: "Creative generated and saved successfully.",
      });
      navigate(`/generate/${created._id || created.id}`, { replace: true });
    } catch (error) {
      setFeedback({
        tone: "error",
        text: error.message || "Something went wrong during generation.",
      });
    } finally {
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
      }
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    if (!generatedCreative?.imageUrl) return;
    const link = document.createElement("a");
    link.href = generatedCreative.imageUrl;
    link.download = `${(generatedCreative.title || "creative").replace(/\s+/g, "-").toLowerCase()}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="generate-page">
      <main className="generate-shell">
        <section className="generate-hero-card">
          <div>
            <h1>Generate Product Creatives with AI</h1>
            <p>
              Transform your product into high-end visuals for ads, websites, &
              social media.
            </p>
          </div>
          <button type="button" className="hero-cta-btn">
            Try Now
            <span aria-hidden="true">→</span>
          </button>
        </section>

        <section className="generate-main-grid">
          <article className="generate-form-card">
            <header>
              <h2>Create Your Campaign Visual</h2>
              <p>
                Define output type, style, and mood to generate ad-ready assets
              </p>
            </header>

            <label className="field-label" htmlFor="title-input">
              Product / Campaign Title
            </label>
            <div className="field-with-counter">
              <input
                id="title-input"
                maxLength={100}
                value={title}
                onChange={(event) => setTitle(event.target.value)}
                placeholder="e.g. Revive Hydration Bottle - Summer Launch"
              />
              <span>{titleCount}/100</span>
            </div>

            <p className="field-label">Output Type</p>
            <div className="output-grid">
              {outputTypes.map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => setOutputType(type)}
                  className={
                    outputType === type ? "output-btn active" : "output-btn"
                  }
                >
                  {type}
                </button>
              ))}
            </div>

            <p className="field-label">Aspect Ratio</p>
            <div className="ratio-grid">
              {ratios.map((ratio) => (
                <button
                  key={ratio}
                  type="button"
                  onClick={() => setAspectRatio(ratio)}
                  className={
                    aspectRatio === ratio ? "ratio-btn active" : "ratio-btn"
                  }
                >
                  {ratio}
                </button>
              ))}
            </div>

            <label className="field-label" htmlFor="style-select">
              Creative Direction
            </label>
            <select
              id="style-select"
              value={thumbnailStyle}
              onChange={(event) => setThumbnailStyle(event.target.value)}
            >
              {styles.map((option) => (
                <option key={option} value={option}>
                  {option}
                </option>
              ))}
            </select>
            <p className="field-hint">
              Controls composition, typography feel, and visual intensity
            </p>

            <p className="field-label">Brand Color Mood</p>
            <div className="color-row">
              {colorSchemes.map((scheme) => (
                <button
                  key={scheme.id}
                  type="button"
                  aria-label={scheme.name}
                  onClick={() => setColorScheme(scheme)}
                  className={
                    colorScheme.id === scheme.id
                      ? "color-chip active"
                      : "color-chip"
                  }
                  style={{ background: scheme.swatch }}
                />
              ))}
            </div>
            <p className="field-hint">Selected: {colorScheme.name}</p>

            <label className="field-label" htmlFor="model-select">
              Model
            </label>
            <select
              id="model-select"
              value={model}
              onChange={(event) => setModel(event.target.value)}
            >
              <option value="premium">Premium (10 credits)</option>
              <option value="advanced">Advanced (7 credits)</option>
              <option value="standard">Standard (3 credits)</option>
            </select>

            <div className="photo-row">
              <div className="photo-icon" aria-hidden="true">
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 12C14.2091 12 16 10.2091 16 8C16 5.79086 14.2091 4 12 4C9.79086 4 8 5.79086 8 8C8 10.2091 9.79086 12 12 12Z"
                    stroke="currentColor"
                    strokeWidth="1.6"
                  />
                  <path
                    d="M4 20C4.8 16.8 7.6 15 12 15C16.4 15 19.2 16.8 20 20"
                    stroke="currentColor"
                    strokeWidth="1.6"
                    strokeLinecap="round"
                  />
                </svg>
              </div>
              <div className="photo-meta">
                <p>
                  Product Image <span>(required)</span>
                </p>
                <label className="upload-btn" htmlFor="photo-upload">
                  Upload Product
                </label>
                <input
                  id="photo-upload"
                  type="file"
                  accept="image/*"
                  onChange={handlePhotoChange}
                />
              </div>
            </div>
            {productImageName && (
              <p className="field-hint">Attached: {productImageName}</p>
            )}

            {feedback.text && (
              <p className={`feedback-banner ${feedback.tone}`}>
                {feedback.text}
              </p>
            )}

            <label className="field-label" htmlFor="additional-prompts">
              Additional Prompts <span>(optional)</span>
            </label>
            <textarea
              id="additional-prompts"
              placeholder="Describe background, lighting, prop ideas, angle, and campaign mood..."
              value={additionalPrompts}
              onChange={(event) => setAdditionalPrompts(event.target.value)}
            />

            <button
              type="button"
              className="generate-btn"
              onClick={handleGenerate}
              disabled={isLoading}
            >
              {isLoading ? "Generating..." : "Generate Marketing Creative"}
            </button>
          </article>

          <article className="generate-preview-card">
            <h2>Preview</h2>
            {isLoading ? (
              <div className="preview-dropzone loading-state">
                <div className="loading-spinner" aria-hidden="true" />
                <h3>Generating your creative</h3>
                <p>{loadingMessages[loadingIndex]}</p>
              </div>
            ) : generatedCreative ? (
              <div className="preview-ready">
                <div className="preview-media-wrap">
                  <img
                    src={generatedCreative.imageUrl}
                    alt="Generated marketing creative preview"
                    className="generated-preview-image"
                  />
                  <div className="preview-overlay">
                    <button
                      type="button"
                      className="download-btn"
                      onClick={handleDownload}
                    >
                      Download Creative
                    </button>
                  </div>
                </div>
                <div className="preview-meta">
                  <p>
                    Creative ID: {generatedCreative._id || generatedCreative.id}
                  </p>
                  <p>
                    {generatedCreative.outputType} •{" "}
                    {generatedCreative.aspectRatio} •{" "}
                    {generatedCreative.thumbnailStyle}
                  </p>
                </div>
              </div>
            ) : (
              <div className="preview-dropzone">
                <div className="preview-icon" aria-hidden="true">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect
                      x="3.5"
                      y="4.5"
                      width="17"
                      height="15"
                      rx="2.5"
                      stroke="currentColor"
                    />
                    <circle cx="9" cy="10" r="2" stroke="currentColor" />
                    <path
                      d="M20 15L15.5 11L8 18"
                      stroke="currentColor"
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
                <h3>Generate your first campaign visual</h3>
                <p>
                  Upload a product image, choose output type, and click Generate
                </p>
                {sourcePreviewUrl && (
                  <img
                    src={sourcePreviewUrl}
                    alt="Selected source product"
                    className="source-preview-thumb"
                  />
                )}
              </div>
            )}
          </article>
        </section>
      </main>
    </div>
  );
};

export default Generate;
